init:
  - git config --global core.autocrlf input

branches:
  only:
  - master

skip_tags: true

before_build:
  - start /d "C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator" /wait AzureStorageEmulator.exe start

cache:
   - C:\Users\appveyor\AppData\Local\NuGet\Cache
   - C:\projects\journalist\packages

build_script:
  - cmd: build.bat

test: off

version: 0.8.0.{build}

artifacts:
  - path: out
    name: out
