// <auto-generated/>
using System.Reflection;

[assembly: AssemblyProductAttribute("Journalist")]
[assembly: AssemblyVersionAttribute("0.7.2")]
[assembly: AssemblyInformationalVersionAttribute("0.7.2")]
[assembly: AssemblyFileVersionAttribute("0.7.2")]
[assembly: AssemblyCompanyAttribute("Anton Mednonogov")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.7.2";
    }
}
