// <auto-generated/>
using System.Reflection;

[assembly: AssemblyProductAttribute("Journalist")]
[assembly: AssemblyVersionAttribute("0.6.8")]
[assembly: AssemblyInformationalVersionAttribute("0.6.8")]
[assembly: AssemblyFileVersionAttribute("0.6.8")]
[assembly: AssemblyCompanyAttribute("Anton Mednonogov")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.6.8";
    }
}
