// <auto-generated/>
using System.Reflection;

[assembly: AssemblyProductAttribute("Journalist")]
[assembly: AssemblyVersionAttribute("0.2.0")]
[assembly: AssemblyInformationalVersionAttribute("0.2.0")]
[assembly: AssemblyFileVersionAttribute("0.2.0")]
[assembly: AssemblyCompanyAttribute("Anton Mednonogov")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.2.0";
    }
}
